name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Elixir
      uses: actions/setup-elixir@v1
      with:
        otp-version: 24.0
        elixir-version: 1.15.2

    - name: Install Dependencies
      run: mix deps.get

    - name: Run Tests
      run: mix test

    - name: Deploy
      run: mix release