name: CI

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.15.2
        otp-version: 26.0.2

    - name: Install Dependencies
      run: mix deps.get

    - name: Run Tests
      run: mix test

  deploy:
    name: Deploy app
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
